### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by hipitihop** [bricej13/node-red-contrib-proxmox#6]
Thanks for this node.  I'm running on node-red 1.0.3 and proxmox 6.1-5 however the node never authenticates. Debug output is:

![image](https://user-images.githubusercontent.com/4626024/71863810-c7a3dd00-3149-11ea-8e76-0f948ce24c38.png)

Suggestions?

**Comment by lighthousebulb** [comment]
same here

**Comment by Sythsaz** [comment]
I also have this issue

**Comment by tuxmeister** [comment]
Pretty sure this node no longer works with modern versions of Proxmox, however interacting with its API is today easier than ever and we don't really need a dedicated Proxmox node to achieve the same.

**Comment by tuxmeister** [comment]
> Thanks for this node. I'm running on node-red 1.0.3 and proxmox 6.1-5 however the node never authenticates. Debug output is:
> 
> ![image](https://user-images.githubusercontent.com/4626024/71863810-c7a3dd00-3149-11ea-8e76-0f948ce24c38.png)
> 
> Suggestions?

For anybody else too: the username format for Proxmox is "$linuxUser@pam", once I added this, authentication was successful. Sorry I doubted this! :D This version of the node doesn't support API token authentication out of the box from what I can tell but should be easy to add...

**Comment by hipitihop** [comment]
> For anybody else too: the username format for Proxmox is "$linuxUser@pam", once I added this, authentication was successful. Sorry I doubted this! :D This version of the node doesn't support API token authentication out of the box from what I can tell but should be easy to add...

@tuxmeister Many, thanks, indeed that works. Closing
